package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.AuthRoles;
import com.rillsoft.springbookadmin.model.AuthUsers;

import java.util.List;

public interface AuthRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    int insert(AuthRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    AuthRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    List<AuthRoles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    int updateByPrimaryKey(AuthRoles record);

    // added by crane zhou on 2021.11.17
    AuthRoles selectByRoleCode(String strRoleCode);
}