package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.AuthRoles;
import com.rillsoft.springbookadmin.model.AuthUserRoles;
import com.rillsoft.springbookadmin.model.AuthUsers;

import java.util.List;

public interface AuthUserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int insert(AuthUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    AuthUserRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    List<AuthUserRoles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int updateByPrimaryKey(AuthUserRoles record);

    // added by crane zhou on 2021.11.03
    List<AuthUserRoles> selectAuthUserRolesByUserId(Integer id);
    List<AuthUserRoles> selectAuthUserRolesByRoleId(Integer id);

    List<AuthRoles> selectAuthRolesByUserId(Integer id);

    // added by crane zhou on 2021.11.20
    int deleteAuthUserRolesByUserId(Integer id);
}