package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.*;

import java.util.List;

public interface AuthUserGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int insert(AuthUserGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    AuthUserGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    List<AuthUserGroups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int updateByPrimaryKey(AuthUserGroups record);

    // added by crane zhou on 2021.11.07
    List<AuthUserGroups> selectAuthUserGroupsByUserId(Integer id);
    List<AuthUserGroups> selectAuthUserGroupsByGroupId(Integer id);

    List<AuthGroups> selectAuthGroupsByUserId(Integer id);

    // added by crane zhou on 2021.11.20
    int deleteAuthUserGroupsByUserId(Integer id);
}