package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.AuthGroups;
import com.rillsoft.springbookadmin.model.AuthRoles;

import java.util.List;

public interface AuthGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    int insert(AuthGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    AuthGroups selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    List<AuthGroups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    int updateByPrimaryKey(AuthGroups record);

    // added by crane zhou on 2021.11.17
    AuthGroups selectByGroupCode(String strGroupCode);
}