package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.AuthUsers;
import java.util.List;

public interface AuthUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int insert(AuthUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    AuthUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    List<AuthUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    int updateByPrimaryKey(AuthUsers record);

    // added by crane zhou on 2021.09.29
    AuthUsers selectByUsername(String strUsername);
    List<AuthUsers> selectByFullname(String strFullname);
}