package com.rillsoft.springbookadmin.mapper;

import com.rillsoft.springbookadmin.model.GoodsCategory;
import java.util.List;

public interface GoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_category
     *
     * @mbg.generated Mon Oct 25 18:46:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_category
     *
     * @mbg.generated Mon Oct 25 18:46:27 CST 2021
     */
    int insert(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_category
     *
     * @mbg.generated Mon Oct 25 18:46:27 CST 2021
     */
    GoodsCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_category
     *
     * @mbg.generated Mon Oct 25 18:46:27 CST 2021
     */
    List<GoodsCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_category
     *
     * @mbg.generated Mon Oct 25 18:46:27 CST 2021
     */
    int updateByPrimaryKey(GoodsCategory record);
}