package com.rillsoft.springbookadmin.model;

import java.io.Serializable;

public class AuthUserRoles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_roles.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_roles.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_roles.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_roles.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public AuthUserRoles(Integer id, Integer userId, Integer roleId, String remark) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_roles
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public AuthUserRoles() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_roles.id
     *
     * @return the value of tbl_auth_user_roles.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_roles.id
     *
     * @param id the value for tbl_auth_user_roles.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_roles.user_id
     *
     * @return the value of tbl_auth_user_roles.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_roles.user_id
     *
     * @param userId the value for tbl_auth_user_roles.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_roles.role_id
     *
     * @return the value of tbl_auth_user_roles.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_roles.role_id
     *
     * @param roleId the value for tbl_auth_user_roles.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_roles.remark
     *
     * @return the value of tbl_auth_user_roles.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_roles.remark
     *
     * @param remark the value for tbl_auth_user_roles.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}