package com.rillsoft.springbookadmin.model;

import java.io.Serializable;

public class AuthUserGroups implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_groups.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_groups.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_groups.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_user_groups.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public AuthUserGroups(Integer id, Integer userId, Integer groupId, String remark) {
        this.id = id;
        this.userId = userId;
        this.groupId = groupId;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_user_groups
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public AuthUserGroups() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_groups.id
     *
     * @return the value of tbl_auth_user_groups.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_groups.id
     *
     * @param id the value for tbl_auth_user_groups.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_groups.user_id
     *
     * @return the value of tbl_auth_user_groups.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_groups.user_id
     *
     * @param userId the value for tbl_auth_user_groups.user_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_groups.group_id
     *
     * @return the value of tbl_auth_user_groups.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_groups.group_id
     *
     * @param groupId the value for tbl_auth_user_groups.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_user_groups.remark
     *
     * @return the value of tbl_auth_user_groups.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_user_groups.remark
     *
     * @param remark the value for tbl_auth_user_groups.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}