package com.rillsoft.springbookadmin.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.*;

// @FieldMatch(first = "password", second = "confirmPassword", message = "The password fields must match"),
public class AuthUsers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.username
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    @NotEmpty(message = "{registration.validation.username}")
    @Size(min=5, max=32)
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.password
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    @NotEmpty(message = "{registration.validation.password}")
    private String password;

//    @NotEmpty(message = "{registration.validation.password}")
//    private String confirmPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.fullname
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */

// commented by crane zhou on 2021.11.15
// (using bootstrap validation temporarily in register.html)
//    @NotEmpty(message = "{registration.validation.fullname}")
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.user_email
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */

    @Email(message = "{registration.validation.userEmail}")
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.user_phone
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.last_login
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.date_joined
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Date dateJoined;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.user_status
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.role_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.group_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.city_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.city_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_users.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public AuthUsers(Integer id, String username, String password, String fullname, String userEmail, String userPhone, Date lastLogin, Date dateJoined, Integer userStatus, Integer roleId, String roleName, Integer groupId, String groupName, Integer cityId, String cityName, String remark) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.userEmail = userEmail;
        this.userPhone = userPhone;
        this.lastLogin = lastLogin;
        this.dateJoined = dateJoined;
        this.userStatus = userStatus;
        this.roleId = roleId;
        this.roleName = roleName;
        this.groupId = groupId;
        this.groupName = groupName;
        this.cityId = cityId;
        this.cityName = cityName;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_users
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
//    public AuthUsers() {
//        super();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.id
     *
     * @return the value of tbl_auth_users.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.id
     *
     * @param id the value for tbl_auth_users.id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.username
     *
     * @return the value of tbl_auth_users.username
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.username
     *
     * @param username the value for tbl_auth_users.username
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.password
     *
     * @return the value of tbl_auth_users.password
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.password
     *
     * @param password the value for tbl_auth_users.password
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.fullname
     *
     * @return the value of tbl_auth_users.fullname
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.fullname
     *
     * @param fullname the value for tbl_auth_users.fullname
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.user_email
     *
     * @return the value of tbl_auth_users.user_email
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.user_email
     *
     * @param userEmail the value for tbl_auth_users.user_email
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.user_phone
     *
     * @return the value of tbl_auth_users.user_phone
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.user_phone
     *
     * @param userPhone the value for tbl_auth_users.user_phone
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.last_login
     *
     * @return the value of tbl_auth_users.last_login
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.last_login
     *
     * @param lastLogin the value for tbl_auth_users.last_login
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.date_joined
     *
     * @return the value of tbl_auth_users.date_joined
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Date getDateJoined() {
        return dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.date_joined
     *
     * @param dateJoined the value for tbl_auth_users.date_joined
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setDateJoined(Date dateJoined) {
        this.dateJoined = dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.user_status
     *
     * @return the value of tbl_auth_users.user_status
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.user_status
     *
     * @param userStatus the value for tbl_auth_users.user_status
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.role_id
     *
     * @return the value of tbl_auth_users.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.role_id
     *
     * @param roleId the value for tbl_auth_users.role_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.role_name
     *
     * @return the value of tbl_auth_users.role_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.role_name
     *
     * @param roleName the value for tbl_auth_users.role_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.group_id
     *
     * @return the value of tbl_auth_users.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.group_id
     *
     * @param groupId the value for tbl_auth_users.group_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.group_name
     *
     * @return the value of tbl_auth_users.group_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.group_name
     *
     * @param groupName the value for tbl_auth_users.group_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.city_id
     *
     * @return the value of tbl_auth_users.city_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.city_id
     *
     * @param cityId the value for tbl_auth_users.city_id
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.city_name
     *
     * @return the value of tbl_auth_users.city_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.city_name
     *
     * @param cityName the value for tbl_auth_users.city_name
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_users.remark
     *
     * @return the value of tbl_auth_users.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_users.remark
     *
     * @param remark the value for tbl_auth_users.remark
     *
     * @mbg.generated Tue Oct 19 17:13:22 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    // added by Crane Zhou on 2021.10.20
//    private Set<AuthRoles> m_objAuthUserRoles= new HashSet<>();
//
//    public void addAuthUserRoles(AuthRoles objTheRoles){
//        m_objAuthUserRoles.add(objTheRoles);
////        objTheRoles.getUsers().add(this);
//    }
//
//    public void removeAuthUserRoles(AuthRoles objTheRoles){
//        m_objAuthUserRoles.remove(objTheRoles);
////        objTheRoles.getUsers().remove(this);
//    }
//
//    public Set<AuthRoles> getAuthUserRoles() {
//        return m_objAuthUserRoles;
//    }
//
//    public void setAuthUserRoles(Set<AuthRoles> objTheRoles) {
//        this.m_objAuthUserRoles = objTheRoles;
//    }

    // added by Crane Zhou on 2021.11.03
    private List<AuthRoles> m_objAuthRoles;     // Not used yet.

    public List<AuthRoles> getAuthRoles() { return m_objAuthRoles; }
    public void setAuthRoles(List<AuthRoles> objTheRoles) {
        this.m_objAuthRoles = objTheRoles;
    }

    // added by crane zhou on 2021.11.17
    public void addAuthRoles(AuthRoles objAuthRoles)
    {
        m_objAuthRoles.add(objAuthRoles);
    }
    public void removeAuthRoles(AuthRoles objAuthRoles)
    {
        m_objAuthRoles.remove(objAuthRoles);
    }

    public boolean isAccountVerified()  { return true; }
    public boolean isLoginDisabled() { return true; }

    // added by crane zhou on 2021.11.16
    // added by Crane Zhou on 2021.11.17
    private List<AuthGroups> m_objAuthGroups;

    public List<AuthGroups> getAuthGroups() { return m_objAuthGroups; }
    public void setAuthGroups(List<AuthGroups> objTheGroups) {
        this.m_objAuthGroups = objTheGroups;
    }

    public void addAuthGroups(AuthGroups objAuthGroup)
    {
        m_objAuthGroups.add(objAuthGroup);
    }
    public void removeAuthGroups(AuthGroups objAuthGroup)
    {
        m_objAuthGroups.remove(objAuthGroup);
    }

    public AuthUsers() {
        super();

        m_objAuthRoles = new ArrayList<>();
        m_objAuthGroups = new ArrayList<>();
    }
//    @Override
//    public String toString() { return "hello world"; }
}