package com.rillsoft.springbookadmin.model;

import java.io.Serializable;

public class AuthGroups implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_groups.id
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_groups.group_name
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_groups.group_code
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private String groupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_groups.group_status
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private Integer groupStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_groups.remark
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public AuthGroups(Integer id, String groupName, String groupCode, Integer groupStatus, String remark) {
        this.id = id;
        this.groupName = groupName;
        this.groupCode = groupCode;
        this.groupStatus = groupStatus;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_groups
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public AuthGroups() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_groups.id
     *
     * @return the value of tbl_auth_groups.id
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_groups.id
     *
     * @param id the value for tbl_auth_groups.id
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_groups.group_name
     *
     * @return the value of tbl_auth_groups.group_name
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_groups.group_name
     *
     * @param groupName the value for tbl_auth_groups.group_name
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_groups.group_code
     *
     * @return the value of tbl_auth_groups.group_code
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_groups.group_code
     *
     * @param groupCode the value for tbl_auth_groups.group_code
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_groups.group_status
     *
     * @return the value of tbl_auth_groups.group_status
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public Integer getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_groups.group_status
     *
     * @param groupStatus the value for tbl_auth_groups.group_status
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public void setGroupStatus(Integer groupStatus) {
        this.groupStatus = groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_groups.remark
     *
     * @return the value of tbl_auth_groups.remark
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_groups.remark
     *
     * @param remark the value for tbl_auth_groups.remark
     *
     * @mbg.generated Wed Nov 17 10:40:27 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}