package com.rillsoft.springbookadmin.model;

import java.io.Serializable;

public class AuthRoles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_roles.id
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_roles.role_name
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_roles.role_code
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_roles.role_status
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private Integer roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth_roles.remark
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public AuthRoles(Integer id, String roleName, String roleCode, Integer roleStatus, String remark) {
        this.id = id;
        this.roleName = roleName;
        this.roleCode = roleCode;
        this.roleStatus = roleStatus;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_auth_roles
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public AuthRoles() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_roles.id
     *
     * @return the value of tbl_auth_roles.id
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_roles.id
     *
     * @param id the value for tbl_auth_roles.id
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_roles.role_name
     *
     * @return the value of tbl_auth_roles.role_name
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_roles.role_name
     *
     * @param roleName the value for tbl_auth_roles.role_name
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_roles.role_code
     *
     * @return the value of tbl_auth_roles.role_code
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_roles.role_code
     *
     * @param roleCode the value for tbl_auth_roles.role_code
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_roles.role_status
     *
     * @return the value of tbl_auth_roles.role_status
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_roles.role_status
     *
     * @param roleStatus the value for tbl_auth_roles.role_status
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth_roles.remark
     *
     * @return the value of tbl_auth_roles.remark
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth_roles.remark
     *
     * @param remark the value for tbl_auth_roles.remark
     *
     * @mbg.generated Wed Nov 03 09:17:05 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}